### ISSUE TITLE
Typography and Fonts

### ISSUE THREAD

**Issue by dak-384** [dak-384/news-website#14]
**Is your feature request related to a problem? Please describe.**
No fonts and font sizes /meaningful hierarchy currently set. 

**Describe the solution you'd like**
Font size can be defined in the html inside a `clamp()` function that will ensure that the user’s preference is not ignored but also that the font size is responsive in different break points and does not respond terribly in the extremes. The clamp function can maybe be as below: 

``` css
html {
    font-size: clamp(1rem, .75rem + 1vw, 1.8rem);
}
```
The addition that is going on in the middle value ensures that the user can resize the text as opposed to if we used a fixed value like `1vw`. 

The design uses maybe 3/4 different weights so it might be useful to use variable fonts to prevent loading so many files. 

**Tasks**
- [x] Responsive font size
- [x] Responsive line height
- [x] Choose fonts
- [x] Prioritise hierarchy
- [x] Preload fonts
- [ ] Use variable fonts 
- [ ] Fallbacks

**Describe alternatives you've considered**
Using media queries but the downside is that media queries will make the font size jump a lot with changes in viewport width.
