### ISSUE TITLE
Responsive Menu

### ISSUE THREAD

**Issue by dak-384** [dak-384/news-website#6]
**Is your feature request related to a problem? Please describe.**
There is currently no menu in the UI header. 

**Describe the solution you'd like**
A responsive menu that folds into a hamburger on smaller screens. 

**Tasks**
- [x] Hamburger menu on small screens
- [x] Full menu on large screens
- [x] Simple animation for the transition 
- [x] Show active and inactive states for menu items
